# Generated by Django 6.0.8 on 2026-08-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossJournalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('include_data_cables', models.BooleanField(default=True)),
                ('include_power_cables', models.BooleanField(default=True)),
                ('include_tags', models.BooleanField(default=True)),
                ('include_ip_addresses', models.BooleanField(default=True)),
                ('include_serial_numbers', models.BooleanField(default=True)),
                ('include_comments', models.BooleanField(default=True)),
                ('excel_layout', models.CharField(default='split', max_length=10)),
                ('excluded_statuses', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
