# Generated by Django 6.0.8 on 2026-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('netbox_cross_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossjournalsettings',
            name='passthrough_device_types',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.devicetype'),
        ),
    ]
