# Generated by Django 6.0.8 on 2026-09-29 07:51

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_cross_journal', '0002_crossjournalsettings_passthrough_device_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('mode', models.CharField(default='auto', max_length=10)),
                ('routing', models.CharField(default='orthogonal', max_length=20)),
                ('positions', models.JSONField(blank=True, default=dict)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'topology layout',
                'verbose_name_plural': 'topology layouts',
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
